---
- name: Configuration de la Topologie Réseau - Mode RSTP
  hosts: switches
  become: yes

  tasks:
    - name: Appliquer la configuration RSTP (écrase les anciens tests)
      ansible.builtin.copy:
        dest: /etc/network/interfaces
        content: |
          # Fichier généré par Ansible - Mode RSTP Actif
          auto lo
          iface lo inet loopback

          auto eth0
          iface eth0
              address {{ ansible_host }}/24
              vrf mgmt

          auto bridge
          iface bridge
              bridge-ports swp1 swp2 swp3
              bridge-stp yes
              bridge-vlan-aware yes
              mstpctl-forcevers rstp

          auto mgmt
          iface mgmt
              address 127.0.0.1/8
              address ::1/128
              vrf-table auto

    - name: Recharger la configuration réseau instantanément
      ansible.builtin.shell: ifreload -a
