---
- name: Configuration des IPs statiques (Tout-en-un)
  hosts: machines
  become: yes
  vars:
    nom_interface: ens34 # Correction du nom de l'interface
    mes_ips:
      "machine1": "192.168.160.111"
      "machine2": "192.168.160.112"
      "machine3": "192.168.160.113"

  tasks:
    - name: Configuration réseau directement dans le fichier interfaces
      ansible.builtin.copy:
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'
        content: |
          auto lo
          iface lo inet loopback
          auto {{ nom_interface }}
          iface {{ nom_interface }} inet static
              address {{ mes_ips[inventory_hostname] }}
              netmask 255.255.255.0

  handlers:
    # On redémarre le réseau en tâche de fond (async) 
    # pour éviter qu'Ansible ne plante quand l'IP change et coupe le SSH.
    - name: Redémarrer le réseau sans bloquer Ansible
      ansible.builtin.shell: sleep 2 && systemctl restart networking
      async: 10
      poll: 0
      ignore_errors: yes
