[switches]
switch1 ansible_host=192.168.195.101 ansible_user=cumulus ansible_password=testtest ansible_become_password=testtest
switch2 ansible_host=192.168.195.102 ansible_user=cumulus ansible_password=testtest ansible_become_password=testtest
switch3 ansible_host=192.168.195.103 ansible_user=cumulus ansible_password=testtest ansible_become_password=testtest

[machines]
machine1 ansible_host=192.168.195.111 ansible_user=debian ansible_password=debian ansible_become_method=su ansible_become_password=root
machine2 ansible_host=192.168.195.112 ansible_user=debian ansible_password=debian ansible_become_method=su ansible_become_password=root
machine3 ansible_host=192.168.195.113 ansible_user=debian ansible_password=debian ansible_become_method=su ansible_become_password=root
