---
---
- name: Nettoyage et Configuration de la Topologie Réseau
  hosts: switches
  become: yes

  tasks:

    - name: Appliquer une configuration interface 
      ansible.builtin.copy:
        dest: /etc/network/interfaces
        content: |
          # Fichier généré par Ansible - Configuration Propre
          auto lo
          iface lo inet loopback

          auto eth0
          iface eth0
              address {{ ansible_host }}/24
              vrf mgmt

          auto bridge
          iface bridge
              bridge-ports swp1 swp2 swp3
              bridge-stp yes
              bridge-vlan-aware yes
              mstpctl-forcevers stp

          auto mgmt
          iface mgmt
              address 127.0.0.1/8
              address ::1/128
              vrf-table auto

    - name: Recharger la configuration réseau
      ansible.builtin.shell: ifreload -a
