---
# === PARTIE SERVEUR ===
- name: Installer le serveur NFS
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  when: inventory_hostname == 'serveur_fichier'

- name: Créer le répertoire à partager
  ansible.builtin.file:
    path: /home/partage
    state: directory
    mode: '0777'
  when: inventory_hostname == 'serveur_fichier'

- name: Exposer les partages (Autorise tout le réseau 192.168.160.0/24)
  ansible.builtin.copy:
    dest: /etc/exports
    content: |
      /home/partage 192.168.160.0/24(rw,sync,no_subtree_check)
  when: inventory_hostname == 'serveur_fichier'
  notify: Relancer NFS

# === PARTIE CLIENTS ===
- name: Installer les outils client NFS
  ansible.builtin.apt:
    name: nfs-common
    state: present
  when: inventory_hostname != 'serveur_fichier'

- name: Créer le point de montage sur les clients
  ansible.builtin.file:
    path: /mnt/nfs_serveur
    state: directory
  when: inventory_hostname != 'serveur_fichier'

- name: Monter le partage NFS
  ansible.posix.mount:
    path: /mnt/nfs_serveur
    src: 192.168.160.150:/home/partage
    fstype: nfs
    state: mounted
  when: inventory_hostname != 'serveur_fichier'
