---
# === TACHES POUR LE SERVEUR ===
- name: Installer le serveur NFS
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes
  when: inventory_hostname in groups['serveur_nfs']

- name: Exposer les partages
  ansible.builtin.copy:
    dest: /etc/exports
    content: |
      /home/partage_machine1 192.168.160.0/26(rw,sync,no_subtree_check)
      /home/partage_machine2 192.168.160.64/26(rw,sync,no_subtree_check)
  when: inventory_hostname in groups['serveur_nfs']
  notify: Relancer NFS

# === TACHES POUR LES CLIENTS ===
- name: Installer les outils client NFS
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: yes
  when: inventory_hostname in groups['clients_nfs']

- name: Monter le dossier distant
  ansible.builtin.mount:
    path: "/mnt/nfs_serveur"
    src: "192.168.160.150:/home/partage_{{ inventory_hostname }}"
    fstype: nfs
    opts: "nfsvers=3,rw,sync"
    state: mounted
  when: inventory_hostname in groups['clients_nfs']
