---
# === CONFIGURATION DES IPS (Masque /26 = 255.255.255.192) ===
- name: Configurer l'IP de production
  ansible.builtin.copy:
    dest: /etc/network/interfaces.d/lan_prod
    content: |
      auto ens34
      iface ens34 inet static
          address {{ item.ip }}
          netmask 255.255.255.192
  loop:
    - { host: 'machine1', ip: '192.168.160.1' }  # OK (VLAN 1)
    - { host: 'machine2', ip: '192.168.160.100' }  # OK (VLAN 2)
  when: inventory_hostname == item.host

# === PARTIE SERVEUR NFS ===
- name: Configuration Serveur
  block:
    # ... (paquets et dossiers) ...
    - name: Exposer les partages (Version 3)
      ansible.builtin.copy:
        dest: /etc/exports
        content: |
          /home/partage_machine1 192.168.160.0/26(rw,sync,no_subtree_check)
          /home/partage_machine2 192.168.160.64/26(rw,sync,no_subtree_check)

# === PARTIE CLIENTS NFS ===
    - name: Monter le dossier distant
      ansible.builtin.mount:
        path: "/mnt/nfs_serveur"
        src: "192.168.160.150:/home/partage_{{ inventory_hostname }}" # IP du serveur (Bond0)
        fstype: nfs
        opts: "nfsvers=3,rw,sync"
        state: mounted
  when: inventory_hostname in groups['clients_nfs']