- name: Configuration Bonding LACP
  hosts: machines
  become: yes
  
  tasks:
    - name: Setup Interfaces
      ansible.builtin.copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback

          auto eth0
          iface eth0 inet dhcp

          auto eth1
          iface eth1 inet manual

          auto eth2
          iface eth2 inet manual

          auto bond0
          iface bond0 inet static
            {% if inventory_hostname == 'machine1' %}
            address 192.168.1.1
            gateway 192.168.1.254
            {% else %}
            address 192.168.2.1
            gateway 192.168.2.254
            {% endif %}
            netmask 255.255.255.0
            bond-slaves eth1 eth2
            bond-mode 4
            bond-miimon 100
            bond-lacp-rate 1

    - name: Restart Network
      ansible.builtin.shell: systemctl restart networking
