[switches]
switch1 ansible_host=192.168.X.101 ansible_user=cumulus ansible_password=testtest
switch2 ansible_host=192.168.X.102 ansible_user=cumulus ansible_password=testtest
switch3 ansible_host=192.168.X.103 ansible_user=cumulus ansible_password=testtest

[serveur_nfs]
serveur_fichier ansible_host=192.168.X.10 ansible_user=root ansible_password=testtest

[clients_nfs]
machine1 ansible_host=192.168.X.11 ansible_user=root ansible_password=testtest
machine2 ansible_host=192.168.X.12 ansible_user=root ansible_password=testtest