[switches]
switch1 ansible_host=192.168.195.201 ansible_user=cumulus ansible_password=testtest ansible_become_password=testtest
switch2 ansible_host=192.168.195.202 ansible_user=cumulus ansible_password=testtest ansible_become_password=testtest
switch3 ansible_host=192.168.195.203 ansible_user=cumulus ansible_password=testtest ansible_become_password=testtest

[serveur_fichier]
serveur_fichier ansible_host=192.168.195.210 ansible_user=debian ansible_password=debian ansible_become_method=su ansible_become_password=root

[clients]
machine1 ansible_host=192.168.195.211 ansible_user=debian ansible_password=debian ansible_become_method=su ansible_become_password=root
machine2 ansible_host=192.168.195.212 ansible_user=debian ansible_password=debian ansible_become_method=su ansible_become_password=root
