[switches]
switch1 ansible_host=192.168.195.201 ansible_user=cumulus ansible_password=testtest
switch2 ansible_host=192.168.195.202 ansible_user=cumulus ansible_password=testtest
switch3 ansible_host=192.168.195.203 ansible_user=cumulus ansible_password=testtest

[serveur_nfs]
serveur_fichier ansible_host=192.168.195.210 ansible_user=root ansible_password=testtest

[clients_nfs]
machine1 ansible_host=192.168.195.211 ansible_user=root ansible_password=testtest
machine2 ansible_host=192.168.195.212 ansible_user=root ansible_password=testtest
