---
- name: Configurer les Switches
  hosts: switches
  become: yes
  roles:
    - config_vlan

- name: Configurer le Serveur
  hosts: serveur_fichier
  become: yes
  roles:
    - config_bond
    - config_nfs

- name: Configurer Machine 1
  hosts: machine1
  become: yes
  tasks:
    - name: IP Prod M1
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/lan_prod
        content: |
          auto ens34
          iface ens34 inet static
              address 192.168.160.1
              netmask 255.255.255.192
              gateway 192.168.160.254
    - name: Forcer l'allumage de la carte M1
      ansible.builtin.shell: |
        /sbin/ip addr flush dev ens34 || true
        /sbin/ifup ens34

- name: Configurer Machine 2
  hosts: machine2
  become: yes
  tasks:
    - name: IP Prod M2
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/lan_prod
        content: |
          auto ens34
          iface ens34 inet static
              address 192.168.160.100
              netmask 255.255.255.192
              gateway 192.168.160.126
    - name: Forcer l'allumage de la carte M2
      ansible.builtin.shell: |
        /sbin/ip addr flush dev ens34 || true
        /sbin/ifup ens34

- name: Monter NFS sur les clients
  hosts: machine1, machine2
  become: yes
  roles:
    - config_nfs
