---
# 1. CONFIGURATION DES SWITCHES (CUMULUS)
- name: Configuration de la Topologie Réseau
  hosts: switches
  become: yes
  tasks:
    - name: Appliquer la config VLAN et Routage
      include_tasks: config_vlan.yml 

# 2. CONFIGURATION DU SERVEUR (BONDING + NFS)
- name: Configuration du Serveur de Fichiers
  hosts: serveur_fichier
  become: yes
  tasks:
    - name: Installer et configurer le Bonding LACP
      include_tasks: config_bond.yml

    - name: Installer et configurer le service NFS
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
      
    - name: Créer le dossier et exporter
      ansible.builtin.shell: |
        mkdir -p /home/partage
        chmod 777 /home/partage
        echo "/home/partage 192.168.160.0/24(rw,sync,no_subtree_check)" > /etc/exports
        exportfs -a
        systemctl restart nfs-kernel-server

# 3. CONFIGURATION DES CLIENTS (IP + MONTAGE)
- name: Configuration des Clients
  hosts: clients
  become: yes
  tasks:
    - name: Configurer l'IP de production (sans casser le SSH)
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/lan_prod
        content: |
          auto ens34
          iface ens34 inet static
              address {{ '192.168.160.1' if inventory_hostname == 'machine1' else '192.168.160.100' }}
              netmask 255.255.255.192
              up ip route add 192.168.160.0/24 via {{ '192.168.160.62' if inventory_hostname == 'machine1' else '192.168.160.126' }} dev ens34 || true

    - name: Activer l'interface et monter le NFS
      ansible.builtin.shell: |
        /sbin/ifup ens34 || true
        mkdir -p /mnt/nfs_serveur
        mount -t nfs 192.168.160.150:/home/partage /mnt/nfs_serveur || true
