---
- name: Charger les taches serveur
  ansible.builtin.include_tasks: serveur.yml
  when: "'serveur_fichier' in group_names"

- name: Charger les taches client
  ansible.builtin.include_tasks: client.yml
  when: "'clients' in group_names"