---
- name: Config Switch 1
  ansible.builtin.shell: "{{ item }}"
  loop:
    - net add bridge bridge ports swp1,swp4
    - net add bond bond0 bond slaves swp2-3
    - net add bridge bridge ports bond0
    - net add bond bond0 bridge access 3
    - net add interface swp1 bridge access 1
    - net add interface swp4 bridge trunk vlans 1,3
    - net commit
  when: inventory_hostname == "switch1"

- name: Config Switch 2
  ansible.builtin.shell: "{{ item }}"
  loop:
    - net add bridge bridge ports swp1,swp2
    - net add interface swp2 bridge access 2
    - net add interface swp1 bridge trunk vlans 2
    - net commit
  when: inventory_hostname == "switch2"

- name: Config Switch 3
  ansible.builtin.shell: "{{ item }}"
  loop:
    - net add bridge bridge ports swp1,swp2
    - net add interface swp1 bridge trunk vlans 1,3
    - net add interface swp2 bridge trunk vlans 2
    - net add vlan 1 ip address 192.168.160.62/26
    - net add vlan 2 ip address 192.168.160.126/26
    - net add vlan 3 ip address 192.168.160.190/26
    - net commit
  when: inventory_hostname == "switch3"

- name: Isolation, bloquer M1 <-> M2
  ansible.builtin.iptables:
    chain: FORWARD
    source: "{{ item.src }}"
    destination: "{{ item.dst }}"
    jump: DROP
  loop:
    - { src: '192.168.160.0/26', dst: '192.168.160.64/26' }
    - { src: '192.168.160.64/26', dst: '192.168.160.0/26' }
  when: inventory_hostname == 'switch3'
