---
- name: Installer le paquet ifenslave
  ansible.builtin.apt:
    name: ifenslave
    state: present

- name: Configurer l'interface agrégée (bond0) et ses interfaces physiques
  ansible.builtin.copy:
    dest: /etc/network/interfaces.d/bond0
    content: |
      auto bond0
      iface bond0 inet static
          address 192.168.160.150
          netmask 255.255.255.192
          gateway 192.168.160.190
          bond-slaves ens33 ens34
          bond-mode 4
          bond-miimon 100
          bond-lacp-rate 1
          bond-xmit-hash-policy layer3+4
          bond-downdelay 200

      auto ens33
      iface ens33 inet manual
          bond-master bond0

      auto ens34
      iface ens34 inet manual
          bond-master bond0

- name: Redémarrer le service réseau pour appliquer le Bonding
  ansible.builtin.service:
    name: networking
    state: restarted
