---
- name: Installer ifenslave
  ansible.builtin.apt:
    name: ifenslave
    state: present

- name: Activer le module noyau bonding
  ansible.builtin.modprobe:
    name: bonding
    state: present

- name: Ecrire la configuration du Bond0 (Simplifiee)
  ansible.builtin.copy:
    dest: /etc/network/interfaces.d/bond0
    content: |
      auto bond0
      iface bond0 inet static
          address 192.168.160.150
          netmask 255.255.255.192
          gateway 192.168.160.190
          bond-slaves ens34 ens35
          bond-mode 4
          bond-miimon 100
          bond-lacp-rate 1
          bond-xmit-hash-policy layer3+4

- name: Vider les IP et relancer le reseau
  ansible.builtin.shell: |
    ip addr flush ens34 || true
    ip addr flush ens35 || true
    systemctl restart networking
  become: yes
