---
- name: Installer ifenslave
  ansible.builtin.apt:
    name: ifenslave
    state: present

- name: Activer le module noyau bonding
  ansible.builtin.modprobe:
    name: bonding
    state: present

- name: Ecrire la configuration du Bond0
  ansible.builtin.copy:
    dest: /etc/network/interfaces.d/bond0
    content: |
      auto bond0
      iface bond0 inet static
          address 192.168.160.150
          netmask 255.255.255.192
          gateway 192.168.160.190
          bond-slaves ens34 ens35
          bond-mode 4
          bond-miimon 100
          bond-lacp-rate 1
          bond-xmit-hash-policy layer3+4

      auto ens34
      iface ens34 inet manual
          bond-master bond0

      auto ens35
      iface ens35 inet manual
          bond-master bond0

- name: Activer bond0 sans toucher a ens33
  ansible.builtin.shell: |
    ifdown ens34 2>/dev/null || true
    ifdown ens35 2>/dev/null || true
    ifdown bond0 2>/dev/null || true

    ip addr flush dev ens34 || true
    ip addr flush dev ens35 || true

    ifup ens34
    ifup ens35
    ifup bond0
  become: yes
