---
- name: Configuration des IPs statiques (Tout-en-un)
  hosts: machines
  become: yes
  vars:
    nom_interface: en34
    # Tableau de correspondance "Nom de la machine" : "Nouvelle IP cible"
    mes_ips:
      "machine1": "192.168.160.11"
      "machine2": "192.168.160.12"
      "machine3": "192.168.160.13"

  tasks:
    - name: Ecrire la configuration réseau directement dans le fichier
      ansible.builtin.copy:
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'
        content: |
          # Fichier généré automatiquement par Ansible
          auto lo
          iface lo inet loopback

          auto {{ nom_interface }}
          iface {{ nom_interface }} inet static
              address {{ mes_ips[inventory_hostname] }}
              netmask 255.255.255.0

      notify: Redémarrer le réseau sans bloquer Ansible

  handlers:
    # On redémarre le réseau en tâche de fond (async) 
    # pour éviter qu'Ansible ne plante quand l'IP change et coupe le SSH.
    - name: Redémarrer le réseau sans bloquer Ansible
      ansible.builtin.shell: sleep 2 && systemctl restart networking
      async: 10
      poll: 0
      ignore_errors: yes