---
- name: Configuration des switches
  hosts: switches
  become: yes
  roles:
    - config_vlan

- name: Configuration du serveur
  hosts: serveur_fichier
  become: yes
  roles:
    - config_bond
    - config_nfs  

- name: Configuration des clients
  hosts: clients
  become: yes
  roles:
    - config_nfs  